# Generated by Django 5.0 on 2024-01-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_personas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HoraOcupada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.capacidadmesa')),
                ('ocupada_horas', models.ManyToManyField(blank=True, to='myapp.horaocupada')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.mesa'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('mesa', 'fecha', 'hora')},
        ),
    ]
