# Generated by Django 5.0 on 2024-01-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_capacidadmesa_horaocupada_mesa_reserva_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='capacidad_mesa',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ocupada_horas',
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='tipo',
            new_name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('cantidad_personas', 'fecha', 'hora')},
        ),
        migrations.DeleteModel(
            name='CapacidadMesa',
        ),
        migrations.DeleteModel(
            name='HoraOcupada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='mesa',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
