# Generated by Django 5.0 on 2024-01-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_mesa_capacidad_mesa_remove_mesa_ocupada_horas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carta',
            old_name='categoria',
            new_name='tipo',
        ),
    ]
