# Generated by Django 5.0 on 2024-01-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_categoria_carta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='tipo',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Postres', 'Postres'), ('Comidas Principales', 'Comidas Principales'), ('Entradas', 'Entradas')], max_length=20),
        ),
    ]
