# Generated by Django 5.0.2 on 2024-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='tipo',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Postres', 'Postres'), ('Comidas', 'Comidas'), ('Entradas', 'Entradas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
